version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    depends_on:
      mongo:
        condition: service_healthy
    links: 
      - mongo
    # restart: always
    # network: 
    #   - myNetwork
    # links:
    #   - mongo2
    # networks:
    #   - node-network
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27017"]
      interval: 30s
      timeout: 10s
      retries: 5
    # networks:
    #   - node-network
  

# networks:
#   node-network:
#     driver: bridge